### ISSUE TITLE
Create Parity Signer Tutorial Video

### ISSUE THREAD

**Issue by DrW3RK** [w3f/w3f-education#16]
Parity Signer - https://www.parity.io/technologies/signer/
Using parity signer with Polkadot JS - https://github.com/paritytech/parity-signer/blob/legacy-4.6.2/docs/tutorials/Recover-Account-Polkadotjs.md
Import existing account - https://github.com/paritytech/parity-signer/blob/legacy-4.6.2/docs/tutorials/Recover-Account-Polkadotjs.md

**Comment by filippoweb3** [comment]
@DrW3RK this has been done.
- [create and restore accounts](https://www.youtube.com/watch?v=hgv1R9mPEXw&t=120s)
- [transfer tokens](https://www.youtube.com/watch?v=gbvrHzr4EDY)

**Comment by DrW3RK** [comment]
Thank you!
